version: "3.7"

services:
  mongo:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data:/data/db

  flask_app:
    build:
      context: .
    container_name: flask_app
    ports:
      - 8080:8080
    depends_on:
      - mongo